src/Entity/Chambre.php
<?php

namespace App\Entity;

use App\Repository\ChambreRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ChambreRepository::class)
 */
class Chambre
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $numero;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $status;

     /**
      * @ORM\Column(type="integer")
      */
     private $Etage;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNumero(): ?string
    {
        return $this->numero;
    }

    public function setNumero(string $numero): self
    {
        $this->numero = $numero;

        return $this;
    }

    public function getStatus(): ?string
    {
        return $this->status;
    }

    public function setStatus(string $status): self
    {
        $this->status = $status;

        return $this;
    }

    public function getEtage(): ?string
    {
        return $this->Etage;
    }

    public function setEtage(string $Etage): self
    {
       $this->Etage = $Etage;

        return $this;
    }

    public function __toString()
        {
            return (string) $this->getId();
        }

}

src/Entity/Employee.php
<?php

namespace App\Entity;

use App\Repository\EmployeeRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass=EmployeeRepository::class)
 */
class Employee implements UserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $username;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->username;
    }

    public function setUsername(string $username): self
    {
        $this->username = $username;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getSalt()
    {
        // not needed when using the "bcrypt" algorithm in security.yaml
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }
}

src/Controller/EmployeeController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class EmployeeController extends AbstractController
{
    /**
     * @Route("/employee", name="employee")
     */
    public function index(): Response
    {
        return $this->render('employee/index.html.twig', [
            'controller_name' => 'EmployeeController',
        ]);
    }
}

src/Controller/HotelController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\Routing\Annotation\Route;
use App\Entity\Chambre;
use App\Entity\Employee;
use Symfony\Component\HttpFoundation\Request;

class HotelController extends AbstractController
{
    /**
     * @Route("/hotel", name="home")
     */
    public function index(): Response
    {
        $repo = $this->getDoctrine()->getRepository(Chambre::class);

        $chambres = $repo->findAll();

        return $this->render('hotel/index.html.twig', [
            'controller_name' => 'HotelController',
            'chambres' => $chambres
        ]);
    }

    /**
     * @Route("/createroom", name="createroom")
     */
     public function createroom() {
        return $this->render('hotel/createroom.html.twig');
    }

    /**
     *@Route("/manager", name="manager")
     */
    public function manager() {
        $repo = $this->getDoctrine()->getRepository(Chambre::class);

                $chambres = $repo->findAll();

                return $this->render('hotel/manager.html.twig', [
                    'controller_name' => 'HotelController',
                    'chambres' => $chambres
                ]);

    }

     /**
      *@Route("/reserve/{id}", name="reserve")
      */
        public function reserver (Request $request, $id) {
                                         $entityManager = $this->getDoctrine()->getManager();
                                         $chambre = $entityManager->getRepository(Chambre::class)->find($id);

                    $chambre = $chambre->setStatus("Occupe");
                    $entityManager->flush();

                    return $this->redirectToRoute('manager');

        }

        /**
         *@Route("/libre/{id}", name="libre")
         */
          public function libre (Request $request, $id) {
                                            $entityManager = $this->getDoctrine()->getManager();
                                            $chambre = $entityManager->getRepository(Chambre::class)->find($id);

                            $chambre = $chambre->setStatus("Libre");
                            $entityManager->flush();

                            return $this->redirectToRoute('manager');

          }

          /**
           *@Route("/netoyage/{id}", name="netoyage")
           */
             public function netoyage (Request $request, $id) {
                                            $entityManager = $this->getDoctrine()->getManager();
                                            $chambre = $entityManager->getRepository(Chambre::class)->find($id);

                             $chambre = $chambre->setStatus("A nettoyer");
                             $entityManager->flush();

                             return $this->redirectToRoute('manager');

             }

        /**
        *@Route("/api/get/employees", name="getEmploye")
        */
        public function () {
          $employe = $this->getDoctrine()->getRepository(Employee::class)->findAll();

          $employetab = array();
          foreach ($employe as $employee){

              $employetab[] = [
                  'username' => $employee->getUsername(),
                  'password' => $employee->getPassword()
              ];
          }


          $response = new JsonResponse($employetab);
          return $response;
        }
}

src/Controller/SecurityController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Http\Authentication\AuthenticationUtils;

class SecurityController extends AbstractController
{
    /**
     * @Route("/login", name="app_login")
     */
    public function login(AuthenticationUtils $authenticationUtils): Response
    {
        // if ($this->getUser()) {
        //     return $this->redirectToRoute('target_path');
        // }

        // get the login error if there is one
        $error = $authenticationUtils->getLastAuthenticationError();
        // last username entered by the user
        $lastUsername = $authenticationUtils->getLastUsername();

        return $this->render('security/login.html.twig', ['last_username' => $lastUsername, 'error' => $error]);
    }

    /**
     * @Route("/logout", name="app_logout")
     */
    public function logout()
    {
        throw new \LogicException('This method can be blank - it will be intercepted by the logout key on your firewall.');
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Welcome!{% endblock %}</title>
        <link rel="stylesheet" href="https://bootswatch.com/4/flatly/bootstrap.min.css">
        {% block stylesheets %}{% endblock %}
    </head>
    <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
        <a class="navbar-brand" href="#">CGPalace</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarColor01">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="/hotel">Accueil
                        <span class="sr-only">(current)</span>
                    </a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="/manager">Chambres</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="/createroom">ChambreCreate</a>
                </li>
            </ul>
        </div>
    </nav>
    <div class="container">
        {% block body %}<img src="HotelSymfony/img/hotel.jpg"/>{% endblock %}
    </div>
        {% block javascripts %}{% endblock %}
    </body>
</html>

templates/employee/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello EmployeeController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Hello {{ controller_name }}! ✅</h1>

    This friendly message is coming from:
    <ul>
        <li>Your controller at <code><a href="{{ 'C:/Users/CLAUDE GABRIEL/HotelSymfony/src/Controller/EmployeeController.php'|file_link(0) }}">src/Controller/EmployeeController.php</a></code></li>
        <li>Your template at <code><a href="{{ 'C:/Users/CLAUDE GABRIEL/HotelSymfony/templates/employee/index.html.twig'|file_link(0) }}">templates/employee/index.html.twig</a></code></li>
    </ul>
</div>
{% endblock %}

templates/hotel/createroom.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hotel 5⭐{% endblock %}

{% block body %}

    <h1>Création Chambre</h1>
    <p>Numéro de chambre : n° <select><option name="6">6</option>
            <option name="7">7</option>
            <option name="8">8</option>
            <option name="9">9</option></select></p>

    <p>Etat de la chambre : Libre (par défaut)</p>
    <br/>
    <br/>
    <button>Créer Chambre</button>


{% endblock %}

templates/hotel/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hotel 5⭐{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Salut {{ controller_name }}! ✅</h1>

    This friendly message is coming from:
    <ul>
        <li>Your controller at <code><a href="{{ 'C:/Users/CLAUDE GABRIEL/HotelSymfony/src/Controller/HotelController.php'|file_link(0) }}">src/Controller/HotelController.php</a></code></li>
        <li>Your template at <code><a href="{{ 'C:/Users/CLAUDE GABRIEL/HotelSymfony/templates/hotel/index.html.twig'|file_link(0) }}">templates/hotel/index.html.twig</a></code></li>
    </ul>
</div>

{% endblock %}

templates/hotel/manager.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hotel 5⭐{% endblock %}

{% block body %}
    </br>
    </br>
    </br>
    <section class="chambres">
        <h1>Nombre de chambre dans l'hotel : {{ chambres|length }}</h1>


        {% if app.user.roles[0] == "ROLE_MANAGER" %}

            <center><p><b>Page du Manager !</b></p></center>
            {% for chambre in chambres %}

                <p>Chambre n° {{ chambre.numero }}, située à l'étage n° {{ chambre.Etage }}. Elle est {{ chambre.status }} !

                    <a href="{{ path('netoyage',{'id' : chambre.id}) }}">A nettoyer</a>

                </p>

            {% endfor %}

        {% endif %}



        {% if app.user.roles[0] == "ROLE_RECEPTIONNISTE" %}

            <center><p><b>Page du Receptionniste!</b></p></center>
            {% for chambre in chambres %}

                {% if chambre.status == "Libre" %}

                    <p>Chambre n° {{ chambre.numero }}, située à l'étage n° {{ chambre.etage }}. Elle est {{ chambre.status }} !

                        <a href="{{ path('reserve',{'id' : chambre.id}) }}">A réserver</a>

                    </p>

                {% endif %}

            {% endfor %}

        {% endif %}



        {% if app.user.roles[0] == "ROLE_EMPLOYEE" %}

            <center><p><b>Page de l'Employee !</b></p></center>
            {% for chambre in chambres %}

                {% if chambre.status == "A nettoyer" %}

                    <p>Chambre n° {{ chambre.numero }}, située à l'étage n° {{ chambre.etage }}. Elle est {{ chambre.status }} !

                        <a href="{{ path('libre',{'id' : chambre.id}) }}">Libre</a>

                    </p>

                {% endif %}

            {% endfor %}

        {% endif %}

    </section>
{% endblock %}

templates/security/login.html.twig
{% extends 'base.html.twig' %}

{% block title %}Log in!{% endblock %}

{% block body %}
<form method="post">
    {% if error %}
        <div class="alert alert-danger">{{ error.messageKey|trans(error.messageData, 'security') }}</div>
    {% endif %}

    {% if app.user %}
        <div class="mb-3">
            You are logged in as {{ app.user.username }}, <a href="{{ path('app_logout') }}">Logout</a>
        </div>
    {% endif %}

    <h1 class="h3 mb-3 font-weight-normal">Please sign in</h1>
    <label for="inputUsername">Username</label>
    <input type="text" value="{{ last_username }}" name="username" id="inputUsername" class="form-control" required autofocus>
    <label for="inputPassword">Password</label>
    <input type="password" name="password" id="inputPassword" class="form-control" required>

    <input type="hidden" name="_csrf_token"
           value="{{ csrf_token('authenticate') }}"
    >

    {#
        Uncomment this section and add a remember_me option below your firewall to activate remember me functionality.
        See https://symfony.com/doc/current/security/remember_me.html

        <div class="checkbox mb-3">
            <label>
                <input type="checkbox" name="_remember_me"> Remember me
            </label>
        </div>
    #}

    <button class="btn btn-lg btn-primary" type="submit">
        Sign in
    </button>
</form>
{% endblock %}